[project]
name = "par-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "great-tables>=0.21.0",
    "numpy>=2.4.4",
    "plotly>=6.7.0",
    "polars>=1.40.1",
    "pyarrow>=24.0.0",
    "stargazer>=0.0.7",
    "statsmodels>=0.14.6",
]
